
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Verify code style (prettier)
        run: |
          npm install --global prettier-plugin-rust prettier
          prettier --check **/*
      
      - name: Building engine (library)
        run: |
          cargo build --lib --verbose --release
      
      - name: Building demo app  (bin)
        run: |
          cargo build --bin engine-demo --verbose  --release

      - name: Linting the app via Cargo clippy 
        run: |
           cargo clippy -- -D warnings